apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-chat
  labels:
    app: simple-chat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-chat
  template:
    metadata:
      labels:
        app: simple-chat
    spec:
      containers:
      - name: app
        image: simple-chat:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4444

---

apiVersion: v1
kind: Service
metadata:
  name: simple-chat-service
spec:
  type: NodePort
  selector:
    app: simple-chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4444
